

from PyQt5 import QtCore, QtGui, QtWidgets
from form222 import Ui_page2
list1=[]

class Ui_MainWindow(object):
    
    def nextw1(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_page2()
        self.ui.setupUi(self.window)
        self.window.show()
        activitylevel=self.activityLevelComboBox.currentIndex()
        name=self.nameLineEdit.text()
        age=self.ageLineEdit.text()
        height=int(self.heightLineEdit.text())
        weight=int(self.ageLineEdit_2.text())
        bmi=((weight)/((height*height)/10000))
        if bmi >=25 and bmi<30:
            list1.append("overweight")
        if bmi>30:
            list1.append("obesity")
        f = open("lisage.txt", "a")
        f.write(age)
        f.close()
        file = open('listss.txt','a')
        for l in list1:
          file.write(l+"\n")
        file.close()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(853, 384)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 0, 781, 331))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(150, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_2.setMouseTracking(False)
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(30, 250, 311, 51))
        self.label_9.setObjectName("label_9")
        self.next1 = QtWidgets.QPushButton(self.frame,  clicked = lambda:self.nextw1())
        self.next1.setGeometry(QtCore.QRect(240, 300, 75, 23))
        self.next1.setObjectName("next1")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 50, 741, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 2, 26, 0)
        self.formLayout.setHorizontalSpacing(8)
        self.formLayout.setVerticalSpacing(21)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.ageLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.ageLabel.setObjectName("ageLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ageLabel)
        self.ageLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ageLineEdit.setObjectName("ageLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ageLineEdit)
        self.heightLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.heightLabel.setObjectName("heightLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.heightLabel)
        self.heightLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.heightLineEdit.setObjectName("heightLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.heightLineEdit)
        self.ageLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.ageLabel_2.setObjectName("ageLabel_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ageLabel_2)
        self.ageLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ageLineEdit_2.setObjectName("ageLineEdit_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ageLineEdit_2)
        self.activityLevelLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.activityLevelLabel.setObjectName("activityLevelLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.activityLevelLabel)
        self.activityLevelComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.activityLevelComboBox.setObjectName("activityLevelComboBox")
        self.activityLevelComboBox.addItem("")
        self.activityLevelComboBox.addItem("")
        self.activityLevelComboBox.addItem("")
        self.activityLevelComboBox.addItem("")
        self.activityLevelComboBox.addItem("")
        self.activityLevelComboBox.addItem("")
        self.activityLevelComboBox.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.activityLevelComboBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 853, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Personal details"))
        self.label_9.setText(_translate("MainWindow", "Exercise: 15-30 minutes of elevated heart rate activity.\n"
"Intense exercise: 45-120 minutes of elevated heart rate activity.\n"
"Very intense exercise: 2+ hours of elevated heart rate activity."))
        self.next1.setText(_translate("MainWindow", "Next"))
        self.nameLabel.setText(_translate("MainWindow", "Name"))
        self.ageLabel.setText(_translate("MainWindow", "Age"))
        self.heightLabel.setText(_translate("MainWindow", "Height"))
        self.ageLabel_2.setText(_translate("MainWindow", "Weight"))
        self.activityLevelLabel.setText(_translate("MainWindow", "Activity Level"))
        self.activityLevelComboBox.setItemText(0, _translate("MainWindow", "Basal Metabolic Rate"))
        self.activityLevelComboBox.setItemText(1, _translate("MainWindow", "Sedentary: little or no excercise"))
        self.activityLevelComboBox.setItemText(2, _translate("MainWindow", "Light: excercise 1-3 times/week"))
        self.activityLevelComboBox.setItemText(3, _translate("MainWindow", "Moderate: excercise 4-5 times/week"))
        self.activityLevelComboBox.setItemText(4, _translate("MainWindow", "Active: daily excercise or intense exercise 3-4 times/week"))
        self.activityLevelComboBox.setItemText(5, _translate("MainWindow", "Very Active: intense excercise 6-7 times/week"))
        self.activityLevelComboBox.setItemText(6, _translate("MainWindow", "Extra Active: very intense exercise daily, or physical job"))
f = open("listss.txt", "a")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
