# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '6.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
list6=[]
from form777 import Ui_y77

class Ui_MainWindow(object):
    def nextw6(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_y77()
        self.ui.setupUi(self.window)
        self.window.show()
        if self.opportunistic_infection.isChecked() == True:
             list6.append('opportunistic_infection')


        if self.cancerrelated_fatigue.isChecked() == True:
             list6.append('cancerrelated_fatigue')



        if self.insomnia.isChecked() == True:
             list6.append('insomnia')


        if self.difficulty_falling_asleep.isChecked() == True:
             list6.append('difficulty_falling_asleep')


        if self.sadness.isChecked() == True:
             list6.append('sadness')


        if self.loss_of_pleasure_in_activities.isChecked() == True:
             list6.append('loss_of_pleasure_in_activities')


        if self.loss_of_interest_in_activities.isChecked() == True:
             list6.append('loss_of_interest_in_activities')


        if self.general_discontent.isChecked() == True:
             list6.append('general_discontent')


        if self.guilt.isChecked() == True:
             list6.append('guilt')


        if self.mood_swings.isChecked() == True:
             list6.append('mood_swings')


        if self.moodiness.isChecked() == True:
             list6.append('moodiness')


        if self.hopelessness.isChecked() == True:
             list6.append('hopelessness')


        if self.anxiety.isChecked() == True:
             list6.append('anxiety')


        if self.nervousness.isChecked() == True:
             list6.append('nervousness')


        if self.fear.isChecked() == True:
             list6.append('fear')


        if self.anger.isChecked() == True:
             list6.append('anger')


        if self.restlessness.isChecked() == True:
             list6.append('restlessness')


        if self.irritability.isChecked() == True:
             list6.append('irritability')


        if self.fever.isChecked() == True:
             list6.append('fever')


        if self.malaise.isChecked() == True:
             list6.append('malaise')


        if self.repeatedly_going_over_thoughts.isChecked() == True:
             list6.append('repeatedly_going_over_thoughts')


        if self.depression.isChecked() == True:
             list6.append('depression')


        if self.unwanted_thoughts.isChecked() == True:
             list6.append('unwanted_thoughts')


        if self.sluggishness.isChecked() == True:
             list6.append('sluggishness')


        if self.hyperactivity.isChecked() == True:
             list6.append('hyperactivity')


        if self.lack_of_concentration.isChecked() == True:
             list6.append('lack_of_concentration')


        if self.panic_attack.isChecked() == True:
             list6.append('panic_attack')


        if self.lethargy.isChecked() == True:
             list6.append('lethargy')


        if self.headache.isChecked() == True:
             list6.append('headache')


        if self.appetite_changes.isChecked() == True:
             list6.append('appetite_changes')


        if self.fatigue.isChecked() == True:
             list6.append('fatigue')


        if self.excessive_hunger.isChecked() == True:
             list6.append('excessive_hunger')


        if self.loss_of_appetite.isChecked() == True:
             list6.append('loss_of_appetite')
        print(list6)
        file = open('listss.txt','a')
        for l in list6:
          file.write(l+"\n")
        file.close()      

                
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 451)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.page6 = QtWidgets.QGroupBox(self.centralwidget)
        self.page6.setGeometry(QtCore.QRect(0, 0, 941, 361))
        self.page6.setAcceptDrops(False)
        self.page6.setAutoFillBackground(True)
        self.page6.setTitle("")
        self.page6.setObjectName("page6")
        self.opportunistic_infection = QtWidgets.QCheckBox(self.page6)
        self.opportunistic_infection.setGeometry(QtCore.QRect(10, 10, 761, 18))
        self.opportunistic_infection.setObjectName("opportunistic_infection")
        self.cancerrelated_fatigue = QtWidgets.QCheckBox(self.page6)
        self.cancerrelated_fatigue.setGeometry(QtCore.QRect(10, 30, 841, 21))
        self.cancerrelated_fatigue.setObjectName("cancerrelated_fatigue")
        self.label = QtWidgets.QLabel(self.page6)
        self.label.setGeometry(QtCore.QRect(20, 50, 281, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page6)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 831, 16))
        self.label_2.setObjectName("label_2")
        self.insomnia = QtWidgets.QCheckBox(self.page6)
        self.insomnia.setGeometry(QtCore.QRect(270, 90, 221, 18))
        self.insomnia.setObjectName("insomnia")
        self.difficulty_falling_asleep = QtWidgets.QCheckBox(self.page6)
        self.difficulty_falling_asleep.setGeometry(QtCore.QRect(10, 90, 221, 18))
        self.difficulty_falling_asleep.setObjectName("difficulty_falling_asleep")
        self.sadness = QtWidgets.QCheckBox(self.page6)
        self.sadness.setGeometry(QtCore.QRect(500, 130, 201, 18))
        self.sadness.setObjectName("sadness")
        self.loss_of_pleasure_in_activities = QtWidgets.QCheckBox(self.page6)
        self.loss_of_pleasure_in_activities.setGeometry(QtCore.QRect(270, 210, 231, 18))
        self.loss_of_pleasure_in_activities.setObjectName("loss_of_pleasure_in_activities")
        self.loss_of_interest_in_activities = QtWidgets.QCheckBox(self.page6)
        self.loss_of_interest_in_activities.setGeometry(QtCore.QRect(500, 210, 251, 18))
        self.loss_of_interest_in_activities.setObjectName("loss_of_interest_in_activities")
        self.general_discontent = QtWidgets.QCheckBox(self.page6)
        self.general_discontent.setGeometry(QtCore.QRect(270, 110, 231, 18))
        self.general_discontent.setObjectName("general_discontent")
        self.guilt = QtWidgets.QCheckBox(self.page6)
        self.guilt.setGeometry(QtCore.QRect(730, 130, 67, 18))
        self.guilt.setObjectName("guilt")
        self.mood_swings = QtWidgets.QCheckBox(self.page6)
        self.mood_swings.setGeometry(QtCore.QRect(10, 110, 221, 18))
        self.mood_swings.setObjectName("mood_swings")
        self.moodiness = QtWidgets.QCheckBox(self.page6)
        self.moodiness.setGeometry(QtCore.QRect(730, 150, 67, 18))
        self.moodiness.setObjectName("moodiness")
        self.hopelessness = QtWidgets.QCheckBox(self.page6)
        self.hopelessness.setGeometry(QtCore.QRect(270, 130, 231, 18))
        self.hopelessness.setObjectName("hopelessness")
        self.anxiety = QtWidgets.QCheckBox(self.page6)
        self.anxiety.setGeometry(QtCore.QRect(10, 150, 231, 18))
        self.anxiety.setObjectName("anxiety")
        self.nervousness = QtWidgets.QCheckBox(self.page6)
        self.nervousness.setGeometry(QtCore.QRect(10, 170, 231, 18))
        self.nervousness.setObjectName("nervousness")
        self.fear = QtWidgets.QCheckBox(self.page6)
        self.fear.setGeometry(QtCore.QRect(270, 150, 221, 18))
        self.fear.setObjectName("fear")
        self.anger = QtWidgets.QCheckBox(self.page6)
        self.anger.setGeometry(QtCore.QRect(500, 150, 191, 18))
        self.anger.setObjectName("anger")
        self.restlessness = QtWidgets.QCheckBox(self.page6)
        self.restlessness.setGeometry(QtCore.QRect(10, 130, 211, 18))
        self.restlessness.setObjectName("restlessness")
        self.irritability = QtWidgets.QCheckBox(self.page6)
        self.irritability.setGeometry(QtCore.QRect(730, 110, 111, 18))
        self.irritability.setObjectName("irritability")
        self.fever = QtWidgets.QCheckBox(self.page6)
        self.fever.setGeometry(QtCore.QRect(270, 170, 231, 18))
        self.fever.setObjectName("fever")
        self.malaise = QtWidgets.QCheckBox(self.page6)
        self.malaise.setGeometry(QtCore.QRect(730, 170, 121, 18))
        self.malaise.setObjectName("malaise")
        self.repeatedly_going_over_thoughts = QtWidgets.QCheckBox(self.page6)
        self.repeatedly_going_over_thoughts.setGeometry(QtCore.QRect(10, 210, 321, 18))
        self.repeatedly_going_over_thoughts.setObjectName("repeatedly_going_over_thoughts")
        self.depression = QtWidgets.QCheckBox(self.page6)
        self.depression.setGeometry(QtCore.QRect(500, 110, 201, 18))
        self.depression.setObjectName("depression")
        self.unwanted_thoughts = QtWidgets.QCheckBox(self.page6)
        self.unwanted_thoughts.setGeometry(QtCore.QRect(730, 210, 191, 18))
        self.unwanted_thoughts.setObjectName("unwanted_thoughts")
        self.sluggishness = QtWidgets.QCheckBox(self.page6)
        self.sluggishness.setGeometry(QtCore.QRect(10, 190, 221, 18))
        self.sluggishness.setObjectName("sluggishness")
        self.hyperactivity = QtWidgets.QCheckBox(self.page6)
        self.hyperactivity.setGeometry(QtCore.QRect(270, 190, 231, 18))
        self.hyperactivity.setObjectName("hyperactivity")
        self.lack_of_concentration = QtWidgets.QCheckBox(self.page6)
        self.lack_of_concentration.setGeometry(QtCore.QRect(10, 230, 221, 18))
        self.lack_of_concentration.setObjectName("lack_of_concentration")
        self.panic_attack = QtWidgets.QCheckBox(self.page6)
        self.panic_attack.setGeometry(QtCore.QRect(500, 190, 241, 18))
        self.panic_attack.setObjectName("panic_attack")
        self.lethargy = QtWidgets.QCheckBox(self.page6)
        self.lethargy.setGeometry(QtCore.QRect(730, 190, 91, 18))
        self.lethargy.setObjectName("lethargy")
        self.headache = QtWidgets.QCheckBox(self.page6)
        self.headache.setGeometry(QtCore.QRect(500, 90, 191, 18))
        self.headache.setObjectName("headache")
        self.appetite_changes = QtWidgets.QCheckBox(self.page6)
        self.appetite_changes.setGeometry(QtCore.QRect(270, 230, 231, 18))
        self.appetite_changes.setObjectName("appetite_changes")
        self.fatigue = QtWidgets.QCheckBox(self.page6)
        self.fatigue.setGeometry(QtCore.QRect(730, 90, 91, 18))
        self.fatigue.setObjectName("fatigue")
        self.excessive_hunger = QtWidgets.QCheckBox(self.page6)
        self.excessive_hunger.setGeometry(QtCore.QRect(500, 230, 191, 18))
        self.excessive_hunger.setObjectName("excessive_hunger")
        self.loss_of_appetite = QtWidgets.QCheckBox(self.page6)
        self.loss_of_appetite.setGeometry(QtCore.QRect(730, 230, 161, 18))
        self.loss_of_appetite.setObjectName("loss_of_appetite")
        self.crying = QtWidgets.QCheckBox(self.page6)
        self.crying.setGeometry(QtCore.QRect(500, 170, 211, 18))
        self.crying.setObjectName("crying")
        self.next6 = QtWidgets.QPushButton(self.page6, clicked=lambda:self.nextw6())
        self.next6.setGeometry(QtCore.QRect(750, 280, 75, 23))
        self.next6.setObjectName("next6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 894, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.opportunistic_infection.setText(_translate("MainWindow", "Have you had any opportunistic infections?"))
        self.cancerrelated_fatigue.setText(_translate("MainWindow", "If you have any form of cancer, do you experience fatigue "))
        self.label.setText(_translate("MainWindow", "due to it?"))
        self.label_2.setText(_translate("MainWindow", "Select the applicable feelings, experiences and conditions:"))
        self.insomnia.setText(_translate("MainWindow", "insomnia"))
        self.difficulty_falling_asleep.setText(_translate("MainWindow", "difficulty falling asleep"))
        self.sadness.setText(_translate("MainWindow", "sadness"))
        self.loss_of_pleasure_in_activities.setText(_translate("MainWindow", "loss of pleasure in activities"))
        self.loss_of_interest_in_activities.setText(_translate("MainWindow", "loss of interest in activities"))
        self.general_discontent.setText(_translate("MainWindow", "general discontent"))
        self.guilt.setText(_translate("MainWindow", "guilt"))
        self.mood_swings.setText(_translate("MainWindow", "mood swings"))
        self.moodiness.setText(_translate("MainWindow", "moodiness"))
        self.hopelessness.setText(_translate("MainWindow", "hopelessness"))
        self.anxiety.setText(_translate("MainWindow", "anxiety"))
        self.nervousness.setText(_translate("MainWindow", "nervousness"))
        self.fear.setText(_translate("MainWindow", "fear"))
        self.anger.setText(_translate("MainWindow", "anger"))
        self.restlessness.setText(_translate("MainWindow", "restlessness"))
        self.irritability.setText(_translate("MainWindow", "irritability"))
        self.fever.setText(_translate("MainWindow", "fever"))
        self.malaise.setText(_translate("MainWindow", "malaise"))
        self.repeatedly_going_over_thoughts.setText(_translate("MainWindow", "repeatedly going over thoughts"))
        self.depression.setText(_translate("MainWindow", "depression"))
        self.unwanted_thoughts.setText(_translate("MainWindow", "unwanted thoughts"))
        self.sluggishness.setText(_translate("MainWindow", "sluggishness"))
        self.hyperactivity.setText(_translate("MainWindow", "hyperactivity"))
        self.lack_of_concentration.setText(_translate("MainWindow", "lack of concentration"))
        self.panic_attack.setText(_translate("MainWindow", "panic attack"))
        self.lethargy.setText(_translate("MainWindow", "lethargy"))
        self.headache.setText(_translate("MainWindow", "headache"))
        self.appetite_changes.setText(_translate("MainWindow", "appetite changes"))
        self.fatigue.setText(_translate("MainWindow", "fatigue"))
        self.excessive_hunger.setText(_translate("MainWindow", "excessive hunger"))
        self.loss_of_appetite.setText(_translate("MainWindow", "loss of appetite"))
        self.crying.setText(_translate("MainWindow", "crying"))
        self.next6.setText(_translate("MainWindow", "Next"))
print(list6)
f = open("listss.txt", "a")
for i in range(0, len(list6)-1):
    f.write(list6[i])
    f.write("\n\n\n\n                         ")
f.close()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
